# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a71666a16258735372bc036bdef1c99"
name = "mantle-sample-jason"
handle = "mantle-sample-jason"
application_url = "https://sen-calculated-meals-lt.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "alumtest-jason.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sen-calculated-meals-lt.trycloudflare.com/auth/callback",
  "https://sen-calculated-meals-lt.trycloudflare.com/auth/shopify/callback",
  "https://sen-calculated-meals-lt.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
